/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChemicalDialog.java
 *
 * Created on Mar 13, 2010, 11:27:44 PM
 */

package xbuild;


import DSSATModel.ChemicalMaterialList;
import DSSATModel.FertilizerMethodList;
import Extensions.Variables;
import FileXModel.ChemicalApplication;
import FileXService.FileXValidationService;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.JXFrame;
import xbuild.Components.InputNumberVerifier;
import xbuild.Components.XColumn;

/**
 *
 * @author Jazzy
 */
public class ChemicalDialog extends javax.swing.JDialog {

    /** Creates new form ChemicalDialog */

    protected ChemicalApplication chemApp;
    protected String CHCOD;
    protected String CHME;
    protected boolean bDay;
    private boolean isOK;

    public ChemicalDialog(java.awt.Frame parent, boolean modal, boolean bDay, ChemicalApplication chemApp) {
        super(parent, modal);
        initComponents();

        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        Dimension winSize = getSize();
        setLocation((screenWidth - winSize.width) / 2 , (screenHeight - winSize.height) / 2);

        this.chemApp = chemApp;
        this.CHCOD = chemApp.CHCOD;
        this.CHME = chemApp.CHME;
        
        this.bDay = bDay;
        
        lbDay.setVisible(bDay);
        txtCDAY.setVisible(bDay);
        lbDate.setVisible(!bDay);
        dpCDATE.setVisible(!bDay);
        jLabel1.setVisible(!bDay);
        
        cbCHCOD.setInit(chemApp, "CHCOD", chemApp.CHCOD, ChemicalMaterialList.GetAll(), 
                new XColumn[] { 
                    new  XColumn("Code", "Code", 100),
                    new  XColumn("Description", "Description", 200)
                }, "Code");
        
        cbCHME.setInit(chemApp, "CHME", chemApp.CHME, FertilizerMethodList.GetAll(), 
                new XColumn[] { 
                    new  XColumn("Code", "Code", 100),
                    new  XColumn("Description", "Description", 200)
                }, "Code");

        LoadChemApp();
        
        isOK = false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpCDATE = new org.jdesktop.swingx.JXDatePicker();
        txtCHAMT = new javax.swing.JFormattedTextField();
        txtCHDEP = new javax.swing.JFormattedTextField();
        txtCHT = new javax.swing.JTextField();
        bnOK = new javax.swing.JButton();
        bnCancel = new javax.swing.JButton();
        lbDate = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();
        jXLabel8 = new org.jdesktop.swingx.JXLabel();
        jLabel1 = new javax.swing.JLabel();
        lbDay = new javax.swing.JLabel();
        txtCDAY = new xbuild.Components.XFormattedTextField();
        cbCHCOD = new xbuild.Components.XDropdownTableComboBox();
        cbCHME = new xbuild.Components.XDropdownTableComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        dpCDATE.setFormats(Variables.getDateFormat());
        dpCDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpCDATEActionPerformed(evt);
            }
        });

        txtCHAMT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtCHAMT.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCHAMT.setInputVerifier(new InputNumberVerifier());

        txtCHDEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtCHDEP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCHDEP.setInputVerifier(new InputNumberVerifier());

        bnOK.setText("OK");
        bnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnOKActionPerformed(evt);
            }
        });

        bnCancel.setText("Cancel");
        bnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnCancelActionPerformed(evt);
            }
        });

        lbDate.setText("Date");

        jXLabel2.setText("Chemical Material");

        jXLabel3.setText("Application Amount");

        jXLabel4.setText("Chemical Application Method");

        jXLabel5.setText("Chemical Application Depth");

        jXLabel6.setText("Chemical Targets");

        jXLabel7.setText("cm");

        jXLabel8.setText("kg/ha");

        jLabel1.setText(Variables.getDateFormatString());

        lbDay.setText("Day");

        txtCDAY.setInputVerifier(new InputNumberVerifier());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(bnOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bnCancel)
                        .addGap(234, 234, 234))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDay))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCHT)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dpCDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCHAMT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jXLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCHDEP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jXLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtCDAY, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cbCHCOD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbCHME, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDay)
                    .addComponent(txtCDAY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dpCDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCHCOD, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCHAMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCHME, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCHDEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCHT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnOK)
                    .addComponent(bnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnOKActionPerformed
        Update();
        isOK = true;
        dispose();
    }//GEN-LAST:event_bnOKActionPerformed

    private void bnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnCancelActionPerformed
        isOK = false;
        dispose();
    }//GEN-LAST:event_bnCancelActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if(!isOK)
            SetNull();
    }//GEN-LAST:event_formWindowClosed

    private void dpCDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpCDATEActionPerformed
        Update();
        
        boolean isValid = FileXValidationService.isAfterSimulationDate(dpCDATE.getDate());
        if (!isValid) {
            JOptionPane.showMessageDialog(new JXFrame(), "Date is defined prior to the start of simulation date.", "ERROR", 0);
        }
    }//GEN-LAST:event_dpCDATEActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnCancel;
    private javax.swing.JButton bnOK;
    private xbuild.Components.XDropdownTableComboBox cbCHCOD;
    private xbuild.Components.XDropdownTableComboBox cbCHME;
    private org.jdesktop.swingx.JXDatePicker dpCDATE;
    private javax.swing.JLabel jLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXLabel jXLabel8;
    private org.jdesktop.swingx.JXLabel lbDate;
    private javax.swing.JLabel lbDay;
    private xbuild.Components.XFormattedTextField txtCDAY;
    private javax.swing.JFormattedTextField txtCHAMT;
    private javax.swing.JFormattedTextField txtCHDEP;
    private javax.swing.JTextField txtCHT;
    // End of variables declaration//GEN-END:variables

    public ChemicalApplication GetData() {
        return chemApp;
    }

    public void SetNull() {
        chemApp = null;
    }

    private void Update() {
        if(bDay)
        {
            try
            {
                chemApp.CDAY = Integer.parseInt(txtCDAY.getText());
            }
            catch(Exception ex)
            {
                chemApp.CDAY = null;
            }
            chemApp.CDATE = null;
        }
        else
        {
            try
            {
                chemApp.CDATE = dpCDATE.getDate();
            }
            catch(Exception ex)
            {
                chemApp.CDATE = null;
            }
            chemApp.CDAY = null;
        }

        try
        {
            chemApp.CHAMT = Float.parseFloat(txtCHAMT.getText());
        }
        catch(Exception ex)
        {
            chemApp.CHAMT = null;
        }

        try
        {
            chemApp.CHDEP = Integer.parseInt(txtCHDEP.getText());
        }
        catch(Exception ex) {
            chemApp.CHDEP = null;
        }
        chemApp.CHT = txtCHT.getText();
    }

    private void LoadChemApp() {
        if(bDay)
        {
            try
            {
                txtCDAY.setText(chemApp.CDAY.toString());
            }
            catch(Exception ex)
            {
                txtCDAY.setText("");
            }
            dpCDATE.setDate(null);
        }
        else
        {
            try
            {
                dpCDATE.setDate(chemApp.CDATE);
            }
            catch(Exception ex)
            {
                dpCDATE.setDate(null);
            }
            txtCDAY.setText("");
        }

        try
        {
            txtCHAMT.setText(chemApp.CHAMT.toString());
        }
        catch(Exception ex) { }
        
        try
        {
            txtCHDEP.setText(chemApp.CHDEP.toString());
        }
        catch(Exception ex) { }
        try
        {
            txtCHT.setText(chemApp.CHT);
        }
        catch(Exception ex) { }
    }

}
