/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HarvestDialog.java
 *
 * Created on Mar 13, 2010, 9:27:36 PM
 */

package xbuild;

import FileXModel.HarvestApplication;
import FileXModel.FileX;
import DSSATModel.GrowthStageList;
import DSSATModel.HarvestComponentList;
import DSSATModel.HarvestSizeList;
import Extensions.Variables;
import FileXService.FileXValidationService;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.JXFrame;
import xbuild.Components.InputNumberVerifier;
import xbuild.Components.XColumn;

/**
 *
 * @author Jazzy
 */
public class HarvestDialog extends javax.swing.JDialog {

    /** Creates new form HarvestDialog */

    protected HarvestApplication harvestApp;
    protected boolean bDay;
    protected String HSTG;
    protected String HCOM;
    protected String HSIZE;
    private boolean isOK;

    public HarvestDialog(java.awt.Frame parent, boolean modal, boolean bDay, HarvestApplication harvestApp) {
        super(parent, modal);
        initComponents();

        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        Dimension winSize = getSize();
        setLocation((screenWidth - winSize.width) / 2 , (screenHeight - winSize.height) / 2);

        this.bDay = bDay;
        this.harvestApp = harvestApp;
        
        this.HSTG = harvestApp.HSTG;
        this.HCOM = harvestApp.HCOM;
        this.HSIZE = harvestApp.HSIZE;    

        lbDay.setVisible(bDay);
        txtHDATE.setVisible(bDay);
        lbDate.setVisible(!bDay);
        dpHDATE.setVisible(!bDay);
        jLabel1.setVisible(!bDay);

        cbHSTG.setInit(harvestApp, "HSTG", harvestApp.HSTG, GrowthStageList.GetAt(FileX.general.crop), 
                new XColumn[] { 
                    new  XColumn("Code", "Code", 100),
                    new  XColumn("Description", "Description", 200)
                }, "Code");
        
        cbHCOM.setInit(harvestApp, "HCOM", harvestApp.HCOM, HarvestComponentList.GetAll(), 
                new XColumn[] { 
                    new  XColumn("Code", "Code", 100),
                    new  XColumn("Description", "Description", 200)
                }, "Code");
        
        cbHSIZE.setInit(harvestApp, "HSIZE", harvestApp.HSIZE, HarvestSizeList.GetAll(), 
                new XColumn[] { 
                    new  XColumn("Code", "Code", 100),
                    new  XColumn("Description", "Description", 200)
                }, "Code");
        LoadHarvestApp();
        
        isOK = false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDay = new org.jdesktop.swingx.JXLabel();
        lbDate = new org.jdesktop.swingx.JXLabel();
        dpHDATE = new org.jdesktop.swingx.JXDatePicker();
        txtHDATE = new javax.swing.JFormattedTextField();
        txtHPC = new javax.swing.JFormattedTextField();
        txtHBPC = new javax.swing.JFormattedTextField();
        bnOK = new javax.swing.JButton();
        bnCancel = new javax.swing.JButton();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();
        jLabel1 = new javax.swing.JLabel();
        cbHSTG = new xbuild.Components.XDropdownTableComboBox();
        cbHCOM = new xbuild.Components.XDropdownTableComboBox();
        cbHSIZE = new xbuild.Components.XDropdownTableComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lbDay.setText("Day");

        lbDate.setText("Date");

        dpHDATE.setFormats(Variables.getDateFormat());
        dpHDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpHDATEActionPerformed(evt);
            }
        });

        txtHDATE.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHDATE.setInputVerifier(new InputNumberVerifier());

        txtHPC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0"))));
        txtHPC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHPC.setInputVerifier(new InputNumberVerifier());

        txtHBPC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0"))));
        txtHBPC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHBPC.setInputVerifier(new InputNumberVerifier());

        bnOK.setText("OK");
        bnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnOKActionPerformed(evt);
            }
        });

        bnCancel.setText("Cancel");
        bnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnCancelActionPerformed(evt);
            }
        });

        jXLabel1.setText("Stage");

        jXLabel2.setText("Component");

        jXLabel3.setText("Size Group");

        jXLabel4.setText("Grain Harvest");

        jXLabel5.setText("Byproduct Takeoff");

        jXLabel6.setText("%");

        jXLabel7.setText("%");

        jLabel1.setText(Variables.getDateFormatString());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbHSTG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bnOK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bnCancel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHBPC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jXLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHPC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jXLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtHDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dpHDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)))
                        .addGap(0, 226, Short.MAX_VALUE))
                    .addComponent(cbHCOM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbHSIZE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dpHDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbHSTG, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbHCOM, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbHSIZE, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHBPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnOK)
                    .addComponent(bnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dpHDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpHDATEActionPerformed
        Update();
        
        boolean isValid = FileXValidationService.isAfterSimulationDate(dpHDATE.getDate());
        if (!isValid) {
            JOptionPane.showMessageDialog(new JXFrame(), "Date is defined prior to the start of simulation date.", "ERROR", 0);
        }
}//GEN-LAST:event_dpHDATEActionPerformed

    private void bnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnOKActionPerformed
        Update();
        isOK = true;
        dispose();
    }//GEN-LAST:event_bnOKActionPerformed

    private void bnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnCancelActionPerformed
        isOK = false;
        dispose();
    }//GEN-LAST:event_bnCancelActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if(!isOK)
            SetNull();
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnCancel;
    private javax.swing.JButton bnOK;
    private xbuild.Components.XDropdownTableComboBox cbHCOM;
    private xbuild.Components.XDropdownTableComboBox cbHSIZE;
    private xbuild.Components.XDropdownTableComboBox cbHSTG;
    private org.jdesktop.swingx.JXDatePicker dpHDATE;
    private javax.swing.JLabel jLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXLabel lbDate;
    private org.jdesktop.swingx.JXLabel lbDay;
    private javax.swing.JFormattedTextField txtHBPC;
    private javax.swing.JFormattedTextField txtHDATE;
    private javax.swing.JFormattedTextField txtHPC;
    // End of variables declaration//GEN-END:variables

    private void Update() {
        if(bDay)
        {
            try
            {
                harvestApp.HDAY = Integer.parseInt(txtHDATE.getText());
            }
            catch(Exception ex)
            {
                harvestApp.HDAY = null;
            }
        }
        else
        {
            try
            {
                harvestApp.HDATE = dpHDATE.getDate();
            }
            catch(Exception ex)
            {
                harvestApp.HDATE = null;
            }
        }

        try
        {
            harvestApp.HPC = Float.parseFloat(txtHPC.getText());
        }
        catch(Exception ex)
        {
            harvestApp.HPC = null;
        }

        try
        {
            harvestApp.HBPC = Float.parseFloat(txtHBPC.getText());
        }
        catch(Exception ex)
        {
            harvestApp.HBPC = null;
        }
    }
    private void LoadHarvestApp() {
        if(bDay)
        {
            try
            {
                txtHDATE.setText(harvestApp.HDAY.toString());
            }
            catch(Exception ex)
            {
                txtHDATE.setText("");
            }
        }
        else
        {
            try
            {
                dpHDATE.setDate(harvestApp.HDATE);
            }
            catch(Exception ex)
            {
                dpHDATE.setDate(null);
            }
        }

        try
        {
            txtHPC.setText(harvestApp.HPC.toString());
        }
        catch(Exception ex)
        {
            txtHPC.setText("");
        }

        try
        {
            txtHBPC.setText(harvestApp.HBPC.toString());
        }
        catch(Exception ex)
        {
            txtHBPC.setText("");
        }
    }

    public HarvestApplication GetData() {
        return harvestApp;
    }

    void SetNull() {
        harvestApp = null;
    }

}
