package xbuild;

import DSSATModel.CropList;
import DSSATModel.Soil;
import DSSATModel.SoilList;
import DSSATModel.SoilProfile;
import Extensions.Utils;
import Extensions.Variables;
import FileXModel.FieldDetail;
import FileXModel.FileX;
import FileXModel.ModelXBase;
import FileXModel.InitialCondition;
import FileXModel.InitialConditionApplication;
import FileXModel.ManagementList;
import FileXService.FileXValidationService;
import java.awt.EventQueue;
import java.awt.event.FocusListener;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.JXFrame;
import xbuild.Components.IXInternalFrame;
import xbuild.Components.InputNumberVerifier;
import xbuild.Components.XColumn;
import xbuild.Events.UpdateLevelEvent;

/**
 *
 * @author Jazzy
 */
public class InitialConditionFrame extends IXInternalFrame {

    private InitialCondition init;
    private int selectedRowIndex = -1;

    public InitialConditionFrame(){
        super();
    }

    
    public InitialConditionFrame(String nodeName){
        super(nodeName);
        
    }
    
    @Override
    protected void initFrame(){
        initComponents();

        init = (InitialCondition) model;

        dpICDAT.Init(init, "ICDAT", init.ICDAT);

        txtICND.Init(init, "ICND", init.ICND);
        txtICREN.Init(init, "ICREN", init.ICREN);
        txtICREP.Init(init, "ICREP", init.ICREP);
        txtICRES.Init(init, "ICRES", init.ICRES);
        txtICRID.Init(init, "ICRID", init.ICRID);
        txtICRIP.Init(init, "ICRIP", init.ICRIP);
        txtICRT.Init(init, "ICRT", init.ICRT);
        txtICWD.Init(init, "ICWD", init.ICWD);
        cbPCR.setInit(init, "PCR", init.PCR, CropList.GetAll(), new XColumn[]{new XColumn("CropName", "Crop Name", 200)}, "CropCode");

        snICRE.Init(init, "ICRE", init.ICRE);
        snICRN.Init(init, "ICRN", init.ICRN);

        for (int i = 0; i < init.GetSize(); i++) {
            DefaultTableModel tbModel = (DefaultTableModel) tbProfile.getModel();
            tbModel.addRow(SetRow(init.GetApp(i)));
        }

        lblLevel.setText("Level " + level.toString());
        txtDescription.Init(init, "ICNAME", init.ICNAME);

        dpProfileDate.Init(init, "ICDAT", init.ICDAT);

        ArrayList<String> soils = new ArrayList<>();
        for (ModelXBase x : FileX.fieldList.GetAll()) {
            FieldDetail f = (FieldDetail) x;
            Soil soil = SoilList.GetAt(f.ID_SOIL);
            if (soil != null) {
                String s = soil.Description + " (" + soil.Code + ")";
                if (!soils.contains(s)) {
                    soils.add(s);
                }
            }
        }
        Collections.sort(soils);
        cbSoil.setInit(null, "", "", soils);
        if (!soils.isEmpty()) {
            cbSoil.setSelectedIndex(0);
        }

        setImage(imagePanel, "InCond2.jpg");
        setRecalculateButtonEnabled();
    }

    /**
     *
     * @param name
     */
    @Override
    public void updatePanelName(String name) {
        FocusListener[] listens = txtDescription.getListeners(FocusListener.class);
        for (FocusListener li : listens) {
            txtDescription.removeFocusListener(li);
        }

        level = 0;
        for (ModelXBase f : FileX.initialList.GetAll()) {
            level++;
            if (getLevel(name) == level) {
                lblLevel.setText("Level " + level.toString());
                txtDescription.setText(getDescription(name));
                break;
            }
        }

        for (FocusListener li : listens) {
            this.addFocusListener(li);
        }
    }
    
    @Override
    public boolean isPrevButtonEnabled(){
        return true;
    }
    @Override
    public boolean isNextButtonEnabled(){
        return true;
    }
    
    @Override
    public boolean isAddButtonEnabled(){
        return true;
    }
    @Override
    public boolean isDeleteButtonEnabled(){
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jXPanel3 = new org.jdesktop.swingx.JXPanel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        txtICRT = new xbuild.Components.XFormattedTextField();
        txtICND = new xbuild.Components.XFormattedTextField();
        cbPCR = new xbuild.Components.XDropdownTableComboBox();
        jXPanel5 = new org.jdesktop.swingx.JXPanel();
        jXLabel10 = new org.jdesktop.swingx.JXLabel();
        jXLabel11 = new org.jdesktop.swingx.JXLabel();
        jXLabel12 = new org.jdesktop.swingx.JXLabel();
        txtICWD = new xbuild.Components.XFormattedTextField();
        txtICRES = new xbuild.Components.XFormattedTextField();
        jXLabel9 = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        dpICDAT = new xbuild.Components.XDatePicker();
        jXPanel4 = new org.jdesktop.swingx.JXPanel();
        snICRN = new xbuild.Components.XSpinner();
        snICRE = new xbuild.Components.XSpinner();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();
        jXLabel8 = new org.jdesktop.swingx.JXLabel();
        imagePanel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jXPanel7 = new org.jdesktop.swingx.JXPanel();
        jXLabel13 = new org.jdesktop.swingx.JXLabel();
        jXLabel14 = new org.jdesktop.swingx.JXLabel();
        jXLabel15 = new org.jdesktop.swingx.JXLabel();
        jXLabel16 = new org.jdesktop.swingx.JXLabel();
        txtICREN = new xbuild.Components.XFormattedTextField();
        txtICREP = new xbuild.Components.XFormattedTextField();
        jXPanel6 = new org.jdesktop.swingx.JXPanel();
        jXLabel17 = new org.jdesktop.swingx.JXLabel();
        jXLabel18 = new org.jdesktop.swingx.JXLabel();
        jXLabel19 = new org.jdesktop.swingx.JXLabel();
        txtICRIP = new xbuild.Components.XFormattedTextField();
        txtICRID = new xbuild.Components.XFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jXPanel2 = new org.jdesktop.swingx.JXPanel();
        jXLabel20 = new org.jdesktop.swingx.JXLabel();
        bnAddLayer = new javax.swing.JButton();
        bnDeleteLayer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProfile = new org.jdesktop.swingx.JXTable();
        jLabel1 = new javax.swing.JLabel();
        dpProfileDate = new xbuild.Components.XDatePicker();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtWater = new javax.swing.JFormattedTextField();
        txtNitrogen = new javax.swing.JFormattedTextField();
        bnRecalculate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbSoil = new xbuild.Components.XComboBox();
        jLabel5 = new javax.swing.JLabel();
        lblLevel = new org.jdesktop.swingx.JXLabel();
        txtDescription = new xbuild.Components.XTextField();
        lblLevel1 = new org.jdesktop.swingx.JXLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jXPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Previous Crop", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jXLabel2.setText("Previous Crop");

        jXLabel3.setText("Root Weight");

        jXLabel4.setText("Nodule Weight");

        jXLabel6.setText("kg/ha");

        jXLabel5.setText("kg/ha");

        txtICRT.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtICRT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtICRT.setInputVerifier(new InputNumberVerifier());

        txtICND.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtICND.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtICND.setInputVerifier(new InputNumberVerifier());

        javax.swing.GroupLayout jXPanel3Layout = new javax.swing.GroupLayout(jXPanel3);
        jXPanel3.setLayout(jXPanel3Layout);
        jXPanel3Layout.setHorizontalGroup(
            jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jXLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jXPanel3Layout.createSequentialGroup()
                            .addComponent(txtICND, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jXLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jXPanel3Layout.createSequentialGroup()
                            .addComponent(txtICRT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jXLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cbPCR, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jXPanel3Layout.setVerticalGroup(
            jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel3Layout.createSequentialGroup()
                .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPCR, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtICRT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtICND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jXPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jXLabel10.setText("Crop Residue");

        jXLabel11.setText("cm");

        jXLabel12.setText("kg/ha");

        txtICWD.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtICWD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0"))));
        txtICWD.setInputVerifier(new InputNumberVerifier());

        txtICRES.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtICRES.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtICRES.setInputVerifier(new InputNumberVerifier());

        jXLabel9.setText("Water Table Depth");

        javax.swing.GroupLayout jXPanel5Layout = new javax.swing.GroupLayout(jXPanel5);
        jXPanel5.setLayout(jXPanel5Layout);
        jXPanel5Layout.setHorizontalGroup(
            jXPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jXLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jXPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXPanel5Layout.createSequentialGroup()
                        .addComponent(txtICWD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jXLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jXPanel5Layout.createSequentialGroup()
                        .addComponent(txtICRES, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jXLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jXPanel5Layout.setVerticalGroup(
            jXPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jXPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtICWD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jXPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtICRES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jXLabel1.setText("Measurement Date");

        dpICDAT.setFormats(Variables.getDateFormat());
        dpICDAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpICDATActionPerformed(evt);
            }
        });
        dpICDAT.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dpICDATPropertyChange(evt);
            }
        });

        jXPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rhizobia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        snICRN.setInputVerifier(new InputNumberVerifier());

        snICRE.setInputVerifier(new InputNumberVerifier());

        jXLabel7.setText("Number");

        jXLabel8.setText("Effectiveness");

        javax.swing.GroupLayout jXPanel4Layout = new javax.swing.GroupLayout(jXPanel4);
        jXPanel4.setLayout(jXPanel4Layout);
        jXPanel4Layout.setHorizontalGroup(
            jXPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jXPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jXPanel4Layout.createSequentialGroup()
                        .addComponent(jXLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(snICRE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jXPanel4Layout.createSequentialGroup()
                        .addComponent(jXLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(snICRN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jXPanel4Layout.setVerticalGroup(
            jXPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel4Layout.createSequentialGroup()
                .addGroup(jXPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(snICRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jXPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(snICRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        imagePanel.setBackground(new java.awt.Color(153, 153, 153));

        jLabel6.setText(Variables.getDateFormatString());

        jXPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Residue", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jXLabel13.setText("N");

        jXLabel14.setText("P");

        jXLabel15.setText("%");

        jXLabel16.setText("%");

        txtICREN.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtICREN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtICREN.setInputVerifier(new InputNumberVerifier());

        txtICREP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtICREP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtICREP.setInputVerifier(new InputNumberVerifier());

        javax.swing.GroupLayout jXPanel7Layout = new javax.swing.GroupLayout(jXPanel7);
        jXPanel7.setLayout(jXPanel7Layout);
        jXPanel7Layout.setHorizontalGroup(
            jXPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel7Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jXPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jXLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jXPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtICREN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtICREP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jXPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jXPanel7Layout.setVerticalGroup(
            jXPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel7Layout.createSequentialGroup()
                .addGroup(jXPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtICREN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtICREP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jXPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Incorporation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jXLabel17.setText("Depth");

        jXLabel18.setText("cm");

        jXLabel19.setText("%");

        txtICRIP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtICRIP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtICRIP.setInputVerifier(new InputNumberVerifier());

        txtICRID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtICRID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtICRID.setInputVerifier(new InputNumberVerifier());

        javax.swing.GroupLayout jXPanel6Layout = new javax.swing.GroupLayout(jXPanel6);
        jXPanel6.setLayout(jXPanel6Layout);
        jXPanel6Layout.setHorizontalGroup(
            jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel6Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jXLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXPanel6Layout.createSequentialGroup()
                        .addComponent(txtICRID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jXLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtICRIP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        jXPanel6Layout.setVerticalGroup(
            jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel6Layout.createSequentialGroup()
                .addGroup(jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtICRIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtICRID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("*");

        javax.swing.GroupLayout jXPanel1Layout = new javax.swing.GroupLayout(jXPanel1);
        jXPanel1.setLayout(jXPanel1Layout);
        jXPanel1Layout.setHorizontalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dpICDAT, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addGroup(jXPanel1Layout.createSequentialGroup()
                        .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jXPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jXPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jXPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jXPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jXPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jXPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jXPanel1Layout.setVerticalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXPanel1Layout.createSequentialGroup()
                        .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dpICDAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jXPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jXPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jXPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(159, 159, 159))
                    .addGroup(jXPanel1Layout.createSequentialGroup()
                        .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(250, 250, 250))))
        );

        jTabbedPane2.addTab("Residue", jXPanel1);

        jXLabel20.setText("Initial Condition for Soil :");

        bnAddLayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Plus.png"))); // NOI18N
        bnAddLayer.setText("Add Layer");
        bnAddLayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnAddLayerActionPerformed(evt);
            }
        });

        bnDeleteLayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Minus.png"))); // NOI18N
        bnDeleteLayer.setText("Delete Layer");
        bnDeleteLayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnDeleteLayerActionPerformed(evt);
            }
        });

        tbProfile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "<html><p align='center'>Depth<br>base of layer<br>cm</p></html>", "<html><p align='center'>Volumetric Water<br>cm<sup>3</sup>/cm<sup>3</sup></p></html>", "<html><p align='center'>Ammonium (NH<sub>4</sub>)<br>g[N]/Mg [soil]</p></html>", "<html><p align='center'>Nitrate (NO<sub>3</sub>)<br>g[N]/Mg [soil]</p></html>"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProfileMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbProfile);

        jLabel1.setText("Measurement Date");

        dpProfileDate.setFormats(Variables.getDateFormat());
        dpProfileDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dpProfileDatePropertyChange(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Edit"));

        jLabel2.setText("<html>Water<br/>(% Available)</html>");

        jLabel3.setText("<html>Nitrogen<br/>(kg/ha)</html>");

        txtWater.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtWater.setInputVerifier(new InputNumberVerifier());
        txtWater.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtWaterFocusLost(evt);
            }
        });
        txtWater.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWaterKeyReleased(evt);
            }
        });

        txtNitrogen.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtNitrogen.setInputVerifier(new InputNumberVerifier());
        txtNitrogen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNitrogenFocusLost(evt);
            }
        });
        txtNitrogen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNitrogenKeyReleased(evt);
            }
        });

        bnRecalculate.setText("Recalculate");
        bnRecalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnRecalculateActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("<html>Note: initial condition data will be overwritten<br/>when you select recalculate</html>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWater, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNitrogen, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(bnRecalculate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNitrogen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bnRecalculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText(Variables.getDateFormatString());

        javax.swing.GroupLayout jXPanel2Layout = new javax.swing.GroupLayout(jXPanel2);
        jXPanel2.setLayout(jXPanel2Layout);
        jXPanel2Layout.setHorizontalGroup(
            jXPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel2Layout.createSequentialGroup()
                .addGroup(jXPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXPanel2Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(jXPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jXLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jXPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jXPanel2Layout.createSequentialGroup()
                                .addComponent(dpProfileDate, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addComponent(cbSoil, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jXPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jXPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jXPanel2Layout.createSequentialGroup()
                                .addComponent(bnAddLayer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bnDeleteLayer))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jXPanel2Layout.setVerticalGroup(
            jXPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel2Layout.createSequentialGroup()
                .addGroup(jXPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jXPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bnDeleteLayer)
                            .addComponent(bnAddLayer)))
                    .addGroup(jXPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jXPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(dpProfileDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jXPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jXLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSoil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Profile", jXPanel2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(84, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(103, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(jPanel2);

        lblLevel.setText("Level");
        lblLevel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtDescription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescriptionFocusLost(evt);
            }
        });

        lblLevel1.setText("Initial Conditions");
        lblLevel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblLevel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLevel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProfileMouseClicked
        if (evt.getClickCount() == 2) {
            final InitialDialog dialog = new InitialDialog(null, true, init.GetApp(tbProfile.getSelectedRow()));
            dialog.show();

            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    InitialConditionApplication initApp = dialog.GetData();
                    if (initApp != null) {
                        DefaultTableModel model = (DefaultTableModel) tbProfile.getModel();

                        Object[] row = SetRow(initApp);
                        for (int n = 0; n < row.length; n++) {
                            model.setValueAt(row[n], tbProfile.getSelectedRow(), n);
                        }
                    }
                    dialog.SetNull();
                }
            });
        } else {
            int nRow = tbProfile.getSelectedRow();

            if (nRow != selectedRowIndex) {
                selectedRowIndex = nRow;
            } else {
                selectedRowIndex = -1;
                tbProfile.clearSelection();
            }
        }
    }//GEN-LAST:event_tbProfileMouseClicked

    private void bnAddLayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnAddLayerActionPerformed
        InitialConditionApplication initCond = null;
        if (selectedRowIndex > 0 && selectedRowIndex < init.GetSize()) {
            InitialConditionApplication tmp = init.GetApp(selectedRowIndex);
            initCond = tmp.Clone();
        } else {
            initCond = new InitialConditionApplication();
        }

        final InitialDialog dialog = new InitialDialog(null, true, initCond);
        dialog.show();

        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                InitialConditionApplication initApp = dialog.GetData();
                if (initApp != null) {
                    init.AddApp(initApp);

                    DefaultTableModel tbModel = (DefaultTableModel) tbProfile.getModel();
                    while (tbModel.getRowCount() > 0) {
                        tbModel.removeRow(0);
                    }

                    for (int i = 0; i < init.GetSize(); i++) {
                        tbModel.addRow(SetRow(init.GetApp(i)));
                    }
                }
                dialog.SetNull();
            }
        });
    }//GEN-LAST:event_bnAddLayerActionPerformed

    private void bnDeleteLayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnDeleteLayerActionPerformed
        int nRow = tbProfile.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tbProfile.getModel();
        model.removeRow(nRow);

        init.RemoveAt(nRow);
    }//GEN-LAST:event_bnDeleteLayerActionPerformed

    private void txtDescriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescriptionFocusLost
        if (txtDescription.getText() == null ? init.ICNAME != null : !txtDescription.getText().equals(init.ICNAME)) {
            listener.myAction(new UpdateLevelEvent(this, "Initial Conditions", "Level " + level + ": " + txtDescription.getText(), level - 1));
        }
    }//GEN-LAST:event_txtDescriptionFocusLost

    private void dpProfileDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dpProfileDatePropertyChange
        Date date = dpProfileDate.getDate();
        dpICDAT.setDate(date);
    }//GEN-LAST:event_dpProfileDatePropertyChange

    private void dpICDATPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dpICDATPropertyChange
        Date date = dpICDAT.getDate();
        dpProfileDate.setDate(date);
    }//GEN-LAST:event_dpICDATPropertyChange

    private void bnRecalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnRecalculateActionPerformed
        if (!"".equals(txtWater.getText()) && "".equals(txtNitrogen.getText())) {
            float water = Utils.ParseFloat(txtWater.getValue());
                    
            if((water < 0 || water > 100) && water != -99){
                JOptionPane.showMessageDialog(this, "Water cen be only between 0 and 100.", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if(water == -99){
                water = 100f;
                JOptionPane.showMessageDialog(this, "Using default value for water.", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
            }
            calculateWater(water);
        } else if ("".equals(txtWater.getText()) && !"".equals(txtNitrogen.getText())) {
            float nitrogen = Utils.ParseFloat(txtNitrogen.getValue());
            if(nitrogen < 0 && nitrogen != -99){
                JOptionPane.showMessageDialog(this, "Nitrogen cen be only positive.", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(nitrogen == -99){
                nitrogen = 25f;
                JOptionPane.showMessageDialog(this, "Using default value for nitrogen.", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
            }
            calculateNitrogen(nitrogen);
        } else if (!"".equals(txtWater.getText()) && !"".equals(txtNitrogen.getText())) {
            float water = Utils.ParseFloat(txtWater.getValue());
            float nitrogen = Utils.ParseFloat(txtNitrogen.getValue());
            
            if((water < 0 || water > 100) && water != -99){
                JOptionPane.showMessageDialog(this, "Water cen be only between 0 and 100.", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(water == -99){
                water = 100f;
                JOptionPane.showMessageDialog(this, "Using default value for water.", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
            }
            
            if(nitrogen < 0 && nitrogen != -99){
                JOptionPane.showMessageDialog(this, "Nitrogen cen be only positive.", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(nitrogen == -99){
                nitrogen = 25f;
                JOptionPane.showMessageDialog(this, "Using default value for nitrogen.", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
            }
            calculateInitialCondition(water, nitrogen);
        }
    }//GEN-LAST:event_bnRecalculateActionPerformed

    private void txtWaterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWaterKeyReleased
        setRecalculateButtonEnabled();
    }//GEN-LAST:event_txtWaterKeyReleased

    private void txtNitrogenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNitrogenKeyReleased
        setRecalculateButtonEnabled();
    }//GEN-LAST:event_txtNitrogenKeyReleased

    private void txtWaterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWaterFocusLost
        String text = txtWater.getText();
        float value = Utils.ParseFloat(txtWater.getText());
        
        if(text.equals("")){
            EventQueue.invokeLater(() -> {
                    txtWater.setText("");
                });
        }        
        else if(value == 0){
            EventQueue.invokeLater(() -> {
                    txtWater.setText("0");
                });
        }
    }//GEN-LAST:event_txtWaterFocusLost

    private void txtNitrogenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNitrogenFocusLost
        String text = txtNitrogen.getText();
        float value = Utils.ParseFloat(txtNitrogen.getText());
        
        if(text.equals("")){
            EventQueue.invokeLater(() -> {
                    txtNitrogen.setText("");
                });
        }        
        else if(value == 0){
            EventQueue.invokeLater(() -> {
                    txtNitrogen.setText("0");
                });
        }
    }//GEN-LAST:event_txtNitrogenFocusLost

    private void dpICDATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpICDATActionPerformed
        boolean isValid = FileXValidationService.isAfterSimulationDate(dpICDAT.getDate());
        if (!isValid) {
            JOptionPane.showMessageDialog(new JXFrame(), "Date is defined prior to the start of simulation date.", "ERROR", 0);
        }
    }//GEN-LAST:event_dpICDATActionPerformed

    private void setRecalculateButtonEnabled() {
        bnRecalculate.setEnabled(!"".equals(txtWater.getText()) || !"".equals(txtNitrogen.getText()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnAddLayer;
    private javax.swing.JButton bnDeleteLayer;
    private javax.swing.JButton bnRecalculate;
    private xbuild.Components.XDropdownTableComboBox cbPCR;
    private xbuild.Components.XComboBox cbSoil;
    private xbuild.Components.XDatePicker dpICDAT;
    private xbuild.Components.XDatePicker dpProfileDate;
    private javax.swing.JLabel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel10;
    private org.jdesktop.swingx.JXLabel jXLabel11;
    private org.jdesktop.swingx.JXLabel jXLabel12;
    private org.jdesktop.swingx.JXLabel jXLabel13;
    private org.jdesktop.swingx.JXLabel jXLabel14;
    private org.jdesktop.swingx.JXLabel jXLabel15;
    private org.jdesktop.swingx.JXLabel jXLabel16;
    private org.jdesktop.swingx.JXLabel jXLabel17;
    private org.jdesktop.swingx.JXLabel jXLabel18;
    private org.jdesktop.swingx.JXLabel jXLabel19;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel20;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXLabel jXLabel8;
    private org.jdesktop.swingx.JXLabel jXLabel9;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXPanel jXPanel2;
    private org.jdesktop.swingx.JXPanel jXPanel3;
    private org.jdesktop.swingx.JXPanel jXPanel4;
    private org.jdesktop.swingx.JXPanel jXPanel5;
    private org.jdesktop.swingx.JXPanel jXPanel6;
    private org.jdesktop.swingx.JXPanel jXPanel7;
    private org.jdesktop.swingx.JXLabel lblLevel;
    private org.jdesktop.swingx.JXLabel lblLevel1;
    private xbuild.Components.XSpinner snICRE;
    private xbuild.Components.XSpinner snICRN;
    private org.jdesktop.swingx.JXTable tbProfile;
    private xbuild.Components.XTextField txtDescription;
    private xbuild.Components.XFormattedTextField txtICND;
    private xbuild.Components.XFormattedTextField txtICREN;
    private xbuild.Components.XFormattedTextField txtICREP;
    private xbuild.Components.XFormattedTextField txtICRES;
    private xbuild.Components.XFormattedTextField txtICRID;
    private xbuild.Components.XFormattedTextField txtICRIP;
    private xbuild.Components.XFormattedTextField txtICRT;
    private xbuild.Components.XFormattedTextField txtICWD;
    private javax.swing.JFormattedTextField txtNitrogen;
    private javax.swing.JFormattedTextField txtWater;
    // End of variables declaration//GEN-END:variables

    private Object[] SetRow(InitialConditionApplication initApp) {
        DecimalFormat df = new DecimalFormat("0.000");
        String val = df.format(initApp.SH2O);

        DecimalFormat df1 = new DecimalFormat("0.00");

        Object[] row = new Object[]{initApp.ICBL, val, df1.format(initApp.SNH4), df1.format(initApp.SNO3)};

        return row;
    }

    private void calculateWater(Float water) {
        Soil soil = getSelectedSoil();

        ArrayList<Float> Water_Calculated = new ArrayList<>();

        int size = soil.GetSoilProfiles().size() - 1;

        for (SoilProfile profile : soil.GetSoilProfiles()) {
            Water_Calculated.add(profile.SLLL + (water / 100.0f) * (profile.SDUL - profile.SLLL));
        }

        tbProfile.removeAll();
        DefaultTableModel tbModel = (DefaultTableModel) tbProfile.getModel();
        while (tbModel.getRowCount() > 0) {
            tbModel.removeRow(0);
        }

        if(init.GetSize() > 0){
            for (int i = 0; i < init.GetSize(); i++) {
                InitialConditionApplication initApp = new InitialConditionApplication();
                InitialConditionApplication app = init.GetApp(i);

                initApp.ICBL = app.ICBL;
                initApp.SH2O = i <= size ? Water_Calculated.get(i) : app.SH2O;
                initApp.SNH4 = app.SNH4;
                initApp.SNO3 = app.SNO3;

                if (i <= size) {
                    app.ICBL = initApp.ICBL;
                    app.SH2O = initApp.SH2O;
                    app.SNH4 = initApp.SNH4;
                    app.SNO3 = initApp.SNO3;
                }

                tbModel.addRow(SetRow(initApp));
            }
        }
        else{
            int i = 0;
            for (SoilProfile profile : soil.GetSoilProfiles()) {
                InitialConditionApplication initApp = new InitialConditionApplication();
                
                initApp.ICBL = profile.SLB;
                initApp.SH2O = Water_Calculated.get(i);
                initApp.SNH4 = profile.SDUL;
                initApp.SNO3 = 66f;
                
                
                tbModel.addRow(SetRow(initApp));
                i++;
            }
        }
    }

    private void calculateNitrogen(Float nitrogen) {
        Soil soil = getSelectedSoil();

        boolean isdataMissing = false;

        ArrayList<Float> Depth_Calculated = new ArrayList<>();
        ArrayList<Float> BulkDensity = new ArrayList<>();

        int size = soil.GetSoilProfiles().size() - 1;

        for (SoilProfile profile : soil.GetSoilProfiles()) {
            Depth_Calculated.add(profile.SLB);
            BulkDensity.add(profile.SBDM);
            if (profile.SBDM == null) {
                isdataMissing = true;
            }
        }

        Float BD_Average = 1.2f;
        if (!isdataMissing) {
            BD_Average = BulkDensity.get(0) * Depth_Calculated.get(0) / Depth_Calculated.get(size);
            for (int i = 1; i < Depth_Calculated.size(); i++) {
                BD_Average += BulkDensity.get(i) * (Depth_Calculated.get(i) - (Depth_Calculated.get(i - 1))) / Depth_Calculated.get(size);
            }
        }

        Float INO3_Calculated = (0.9f * nitrogen) / (0.1f * BD_Average * Depth_Calculated.get(size));
        Float INH4_Calculated = (0.1f * nitrogen) / (0.1f * BD_Average * Depth_Calculated.get(size));

        tbProfile.removeAll();
        DefaultTableModel tbModel = (DefaultTableModel) tbProfile.getModel();
        while (tbModel.getRowCount() > 0) {
            tbModel.removeRow(0);
        }

        for (int i = 0; i <= init.GetSize(); i++) {
            InitialConditionApplication initApp = new InitialConditionApplication();
            InitialConditionApplication app = init.GetApp(i);

            initApp.ICBL = app.ICBL;
            initApp.SH2O = app.SH2O;
            initApp.SNH4 = i <= size ? INH4_Calculated : app.SNH4;
            initApp.SNO3 = i <= size ? INO3_Calculated : app.SNO3;

            tbModel.addRow(SetRow(initApp));

            if (i <= size) {
                app.SH2O = initApp.SH2O;
                app.SNH4 = initApp.SNH4;
                app.SNO3 = initApp.SNO3;
            }
        }
    }

    private void calculateInitialCondition(Float water, Float nitrogen) {
        Soil soil = getSelectedSoil();
        boolean isdataMissing = false;

        ArrayList<Float> Depth_Calculated = new ArrayList<>();
        ArrayList<Float> Water_Calculated = new ArrayList<>();
        ArrayList<Float> BulkDensity = new ArrayList<>();

        int size = soil.GetSoilProfiles().size() - 1;

        for (SoilProfile profile : soil.GetSoilProfiles()) {
            Depth_Calculated.add(profile.SLB);
            Water_Calculated.add(profile.SLLL + (water / 100.0f) * (profile.SDUL - profile.SLLL));
            BulkDensity.add(profile.SBDM);
            if (profile.SBDM == null) {
                isdataMissing = true;
            }
        }

        Float BD_Average = 1.2f;
        if (!isdataMissing) {
            BD_Average = BulkDensity.get(0) * Depth_Calculated.get(0) / Depth_Calculated.get(size);
            for (int i = 1; i < Depth_Calculated.size(); i++) {
                BD_Average += BulkDensity.get(i) * (Depth_Calculated.get(i) - (Depth_Calculated.get(i - 1))) / Depth_Calculated.get(size);
            }
        }

        Float INO3_Calculated = (0.9f * nitrogen) / (0.1f * BD_Average * Depth_Calculated.get(size));
        Float INH4_Calculated = (0.1f * nitrogen) / (0.1f * BD_Average * Depth_Calculated.get(size));

        tbProfile.removeAll();
        DefaultTableModel tbModel = (DefaultTableModel) tbProfile.getModel();
        while (tbModel.getRowCount() > 0) {
            tbModel.removeRow(0);
            init.RemoveAt(0);
        }

        for (int i = 0; i <= size; i++) {
            InitialConditionApplication initApp = new InitialConditionApplication();

            initApp.ICBL = Depth_Calculated.get(i);
            initApp.SH2O = Water_Calculated.get(i);
            initApp.SNH4 = INH4_Calculated;
            initApp.SNO3 = INO3_Calculated;

            tbModel.addRow(SetRow(initApp));
            init.AddApp(initApp);
        }
    }
    
    private Soil getSelectedSoil(){
        Soil soil = null;// = SoilList.GetAt(field.ID_SOIL);
        
        String selectedSoil = cbSoil.getSelectedItem().toString();
        for (ModelXBase x : FileX.fieldList.GetAll()) {
            FieldDetail f = (FieldDetail) x;
            Soil s = SoilList.GetAt(f.ID_SOIL);
            if (s != null) {
                String so = s.Description + " (" + s.Code + ")";
                if (so.equalsIgnoreCase(selectedSoil) ) {
                    soil = s;
                    break;
                }
            }
        }
        
        return soil;
    }

    @Override
    public ManagementList getManagementList() {
        return FileX.initialList;
    }
    
    @Override
    public String getManagementName() {
        return "Initial Conditions";
    }
    
    @Override
    public int getLevel(){
        return level;
    }
    
    @Override
    public void initialData(){
        calculateInitialCondition(100f, 25f);
    }

    @Override
    public String getParentName() {
        return "Environment";
    }

    @Override
    public ModelXBase newModel() {
        return new InitialCondition();
    }

    @Override
    public boolean isModelValid() {
        return FileXValidationService.isInitialConditionValid((InitialCondition) model);
    }
}