/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TillageDialog.java
 *
 * Created on Mar 13, 2010, 11:00:44 AM
 */

package xbuild;

import DSSATModel.TillageImplementList;
import Extensions.Variables;
import FileXModel.TillageApplication;
import FileXService.FileXValidationService;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.JXFrame;
import xbuild.Components.InputNumberVerifier;
import xbuild.Components.XColumn;

/**
 *
 * @author Jazzy
 */
public class TillageDialog extends javax.swing.JDialog {

    /** Creates new form TillageDialog */

    protected TillageApplication tilApp;
    protected String TIMPL;
    protected boolean bDay;
    private boolean isOK;

    public TillageDialog(java.awt.Frame parent, boolean modal, boolean bDay, TillageApplication tilApp) {
        super(parent, modal);
        initComponents();

        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        Dimension winSize = getSize();
        setLocation((screenWidth - winSize.width) / 2 , (screenHeight - winSize.height) / 2);

        this.tilApp = tilApp;
        this.TIMPL = tilApp.TIMPL;
        
        this.bDay = bDay;
        
        lbDay.setVisible(bDay);
        txtTDAY.setVisible(bDay);
        lbDate.setVisible(!bDay);
        dpTDATE.setVisible(!bDay);
        jLabel1.setVisible(!bDay);
        
        cbTIMPL.setInit(tilApp, "TIMPL", tilApp.TIMPL, TillageImplementList.GetAll(), 
                new XColumn[] { 
                    new  XColumn("Code", "Code", 100),
                    new  XColumn("Description", "Description", 200)
                }, "Code");

        LoadApp();
        isOK = false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpTDATE = new org.jdesktop.swingx.JXDatePicker();
        txtTDEP = new javax.swing.JFormattedTextField();
        bnOK = new javax.swing.JButton();
        bnCancel = new javax.swing.JButton();
        lbDate = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTDAY = new xbuild.Components.XFormattedTextField();
        lbDay = new javax.swing.JLabel();
        cbTIMPL = new xbuild.Components.XDropdownTableComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        dpTDATE.setFormats(Variables.getDateFormat());
        dpTDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpTDATEActionPerformed(evt);
            }
        });

        txtTDEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtTDEP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTDEP.setInputVerifier(new InputNumberVerifier());

        bnOK.setText("OK");
        bnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnOKActionPerformed(evt);
            }
        });

        bnCancel.setText("Cancel");
        bnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnCancelActionPerformed(evt);
            }
        });

        lbDate.setText("Date");

        jXLabel2.setText("Tillage Implement");

        jXLabel3.setText("Tillage Depth");

        jLabel1.setText(Variables.getDateFormatString());

        txtTDAY.setInputVerifier(new InputNumberVerifier());

        lbDay.setText("Day");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bnOK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bnCancel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dpTDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1))
                            .addComponent(txtTDEP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTDAY, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 161, Short.MAX_VALUE))
                    .addComponent(cbTIMPL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTDAY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dpTDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTIMPL, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTDEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnOK)
                    .addComponent(bnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnOKActionPerformed
        Update();
        isOK = true;
        dispose();
    }//GEN-LAST:event_bnOKActionPerformed

    private void bnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_bnCancelActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if(!isOK)
            SetNull();
    }//GEN-LAST:event_formWindowClosed

    private void dpTDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpTDATEActionPerformed
        Update();
        
        boolean isValid = FileXValidationService.isAfterSimulationDate(dpTDATE.getDate());
        if (!isValid) {
            JOptionPane.showMessageDialog(new JXFrame(), "Date is defined prior to the start of simulation date.", "ERROR", 0);
        }
    }//GEN-LAST:event_dpTDATEActionPerformed

    private void Update() {
        if(bDay)
        {
            try
            {
                tilApp.TDAY = Integer.parseInt(txtTDAY.getText());
            }
            catch(Exception ex)
            {
                tilApp.TDAY = null;
            }
            tilApp.TDATE = null;
        }
        else
        {
            try
            {
                tilApp.TDATE = dpTDATE.getDate();
            }
            catch(Exception ex)
            {
                tilApp.TDATE = null;
            }
            tilApp.TDAY = null;
        }
        
        try
        {
            tilApp.TDEP =Integer.parseInt(txtTDEP.getText());
        }
        catch(Exception ex)
        {
            tilApp.TDEP = null;
        }

    }

    private void LoadApp() {
        if(bDay)
        {
            try
            {
                txtTDAY.setText(tilApp.TDAY.toString());
            }
            catch(Exception ex)
            {
                txtTDAY.setText("");
            }
            dpTDATE.setDate(null);
        }
        else
        {
            try
            {
                dpTDATE.setDate(tilApp.TDATE);
            }
            catch(Exception ex)
            {
                dpTDATE.setDate(null);
            }
            txtTDAY.setText("");
        }

        try
        {
            txtTDEP.setText(tilApp.TDEP.toString());
        }
        catch(Exception ex)
        {
            txtTDEP.setText("");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnCancel;
    private javax.swing.JButton bnOK;
    private xbuild.Components.XDropdownTableComboBox cbTIMPL;
    private org.jdesktop.swingx.JXDatePicker dpTDATE;
    private javax.swing.JLabel jLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel lbDate;
    private javax.swing.JLabel lbDay;
    private xbuild.Components.XFormattedTextField txtTDAY;
    private javax.swing.JFormattedTextField txtTDEP;
    // End of variables declaration//GEN-END:variables

    TillageApplication GetData() {
        return tilApp;
    }

    void SetNull() {
        tilApp = null;
    }
}
