package FileXModel;

public enum Section {
    GeneralNote,
    Field1,
    Field2,
    Field3,
    Soil1,
    Soil2,
    InitialCondition1,
    InitialCondition2,
    Treatment,
    Chemical,
    Cultivar,
    Environment,
    Fertilizer,
    Harvest,
    Irrigation1,
    Irrigation2,
    Planting,
    Organic,
    Tillage,
    Simulation1,
    Simulation2,
    Simulation3,
    Simulation4,
    Simulation5,
    Simulation6,
    Simulation7,
    Simulation8,
    Simulation9,
    Simulation10,
    Simulation11
}
